### ISSUE TITLE
Modify maximum item stack command

### ISSUE THREAD

**Issue by devinaxo** [ThatFinnDev/SR2Essentials#8]
**What should the command do?**
A command to change the maximum amount for each item held in the toolbar would be real nice, I think. Something like "stacklimit [stack amount]".

**Additional context**
It should change each and every slot in the toolbar to reflect that new maximum limit. (Didn't know what to add here)

**Comment by ThatFinnDev** [comment]
There is already a mod called "Vac Modifications", that does that thing. You can't change the stack size via a command, but you can change it via the mod config tab in the mod menu

**Comment by devinaxo** [comment]
Ah, sorry for assuming it could be done and thank you for recommending that mod. Cheers
